# Generated by Django 5.0 on 2025-11-21 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accommodations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="type",
            field=models.CharField(
                choices=[("apartment", "Apartment"), ("hotel", "Hotel")],
                default="apartment",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
