# Generated by Django 5.0 on 2025-11-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_accommodation_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'ordering': ['id']},
        ),
    ]
