# Generated by Django 5.0 on 2025-11-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_voicenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicenote',
            name='file_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voicenote',
            name='file_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
