# Generated by Django 5.0 on 2025-11-25 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0004_voicenote_file_name_voicenote_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="voicenote",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
